### ISSUE TITLE
No storyboard

### ISSUE THREAD

**Issue by fabiosoft** [tomohisa/JTCAdBaseViewController#1]
i tried to make it working, but in my project i use classic xib files....how can i make it working?
I love your ad switcher....

**Comment by tomohisa** [comment]
thanks for the request. It should work with little more code, so I will try to add xib support soon.

**Comment by fabiosoft** [comment]
Thanks! I appreciate...

**Comment by tomohisa** [comment]
I've add AdBaseViewSampleXIB for xib support. check new master branch.
